name: Generator client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build clients"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2
        if: startsWith(runner.os, 'Linux')
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      - name: Generator client for typescript
        run: |
          curl -o openapi.json https://iperon.info/api/v1/openapi.json
          npm install @openapitools/openapi-generator-cli -g
          openapi-generator-cli generate --generator-key typescript

      - name: Install a project with a clean slate
        working-directory: output/typescript/
        run: |
          npm install
          npm ci

      - name: Publish code
        working-directory: output/typescript/
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
