name: Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build clients"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          curl -o openapi.json https://iperon.info/api/v1/openapi.json
          ls -ls
          npm install @openapitools/openapi-generator-cli -g
          openapi-generator-cli generate --generator-key typescript
          ls -ls
